POST http://localhost:8083/connectors
Content-Type: application/json

{
	"name": "file-sink",
	"config": {
        "connector.class": "org.apache.kafka.connect.file.FileStreamSinkConnector",
        "file": "/data/test.sink.txt",
        "tasks.max": "1",
        "topics": "testing",
        "flush.size": "100",
        "rotate.interval.ms": "1000"
    }
}

###

POST http://localhost:8083/connectors
Content-Type: application/json

{
  "name": "file-source",
  "config": {
    "connector.class": "org.apache.kafka.connect.file.FileStreamSourceConnector",
    "file": "/data/test.source.txt",
    "tasks.max": "1",
    "topic": "testing",
    "flush.size": "100",
    "rotate.interval.ms": "1000"
  }
}
